sklep/urls.py
from django.urls import path

from . import views
from django.contrib.auth import views as auth_views

app_name = 'sklep'
urlpatterns = [
    path('',views.base,name='base'), 
    #path('specifics/<int:produkt_id>/',views.detail, name='detail'),
    
    path('produkt/<int:produkt_id>/',views.produkt_details,name='produkt_details'), #Marcin
    path('produkt/<int:produkt_id>/add_opinion',views.add_opinion_on_produkt,name='add_opinion_on_produkt'), #Karolina
    path('produkt/<int:produkt_id>/add_to_cart',views.add_to_cart,name='add_to_cart'), #Marcin

    path('user_profile/',views.user_profile_view,name='user_profile'), #zmiana hasla Sroczyk
    path('update_user_password/',views.update_user_password,name='update_user_password'), #Sroczyk

    path('register/',views.register,name='register'), #Basznianin
    path('login_user/',views.login_view,name='login_user'), #Marcin
    path('logout_user/',views.logout_view,name='logout_user'), #Marcin

    path('shopping_cart/',views.shopping_cart,name='shopping_cart'), #Basznianin
    path('shopping_cart/update__item/',views.updateItem,name='update_item'),#Basznianin
    path('delete_from_cart/',views.delete_from_cart,name='delete_from_cart'), #Basznianin
    path('address_selection/',views.address_selection,name='address_selection'), #Kateryna
    path('address_selection/update_shipping_item/',views.updateShippingItem,name='update_shipping_item'), #Kateryna
    path('checkout/',views.checkout,name='checkout'), #Kateryna
    path('order_summary/',views.order_summary,name='order_summary'), #Kateryna
    

    #path('decrease_amout_of_produkt',views.decrease_amount_of_produkt,name='decrease_amount'),
    #path('increase_amout_of_produkt',views.increase_amount_of_produkt,name='increase_amount'),

    path('searchProduct/', views.searchBar, name='searchProduct'), #Karolina

    path('user_site/',views.user_view ,name='user_view'), #Maciek
    path('user_site/fav_products', views.FavProducts.as_view(), name='fav_view'),  #Dawid
    path('orders_site/',views.orders_view,name='orders_view'), #Grzesiu
    path('add_adres/',views.add_adres,name='add_adres'), #Maciek
    path('adres/<int:adres_id>/',views.egz_adres_modify_view,name="adres_mod"), #Maciek
    path('adres_del/<int:adres_id>/',views.del_adres,name="del_adres"), #Maciek
    path('user_mod/',views.user_dat_mod,name='user_dat_mod'), #Maciek
    path('zamowienie_szcz/<int:id_zamowienia>/',views.zamowienie_szcz,name='order_detail'), #Grzesiu

    path('filtr/<str:filter>/',views.filter_view,name='filter_view'),#Kercz
    path('usuwanie_konta/<int:id>/',views.del_user,name='delete_account'),#Grzesiu
    path('usuwanie_konta_2',views.del_user_page,name='delete_account_page'),#Grzesiu


    path('add_credit_card/',views.add_credit_card,name='add_credit_card'), #Kercz
    path('credit/<int:kartyplatnicze_id>/',views.egz_credit_modify_view,name="credit_card_mod"), #Grzesiu
    path('credit_del/<int:kartyplatnicze_id>/',views.del_credit,name="del_credit"), #Grzesiu
    path('kontakt/',views.kontakt, name='kontakt'), #Sroczyk
    path('faq/', views.Faq.as_view(), name="faq" ), #Dawid
    path('faq/delete/<int:question_id>', views.DeleteQuestion.as_view(), name="delete_faq") #Dawid

]

sklep/templates/sklep/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" text="type/css" href="{% static 'sklep/base/base.css' %}">
    <link href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.css"  rel="stylesheet"  type='text/css'>
    {% block style %}{% endblock %}
    <title>{% block title %}ProjektIO {% endblock %}</title>
    <script type="text/javascript">
        var user = '{{ request.user }}'
        function getToken(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        const csrftoken = getToken('csrftoken');
    </script>
    
</head>

<body>
    <div class="header">
        {%include 'sklep/base/nav.html'%}
    </div>
    
    <div class="containerforbackground">
        <div class="container">
            {% block content %}
            <div id="product-information">
                <p>
                    Nasze produkty
                </p>
            </div>
            <div class="product-wrapper" id="product-wrapper">
                <div id="products">
                    {% for produkt in produkt_list %}
                    <div id="product">
                        <div class="product-image">
                            <img src="{{ produkt.zdjecie_glowne.url }}">
                        </div>
                        <div class="product-information">
                            <div class="product-name">
                                <a class="product-name-style" href="{% url 'sklep:produkt_details' produkt.id %}">{{ produkt.marka }} {{ produkt.model }}</a>
                            </div>
                            <div class="product-price">{{ produkt.cena }} zł</div>
                            <div class="product-category">{{ produkt.podkategoria.nazwa }}</div>
                        </div>
                        <button id="{{produkt.id}}" class="add-to-fav-btn">{%csrf_token%}
                            {%if produkt in fav_products %}
                            Usuń z ulubionych
                            {% else %}
                            Dodaj do ulubionych
                            {% endif %}
                        </button>
                    </div>
                    {% endfor %}
                    {%csrf_token%}
                    <script>
                        const prod_wrapper = document.querySelector('.product-wrapper')
                        const btns = prod_wrapper.querySelectorAll('button')
                        for (let i=0; i<btns.length; i++){
                            const token = '{{csrf_token}}'
                            btns[i].addEventListener('click', () => {
                                data = JSON.stringify({
                                    id: btns[i].id
                                })
                                fetch("user_site/fav_products", {
                                    method: 'POST',
                                    headers: {"X-CSRFToken": token},
                                    body: data
                                }).then((res) => {
                                    if(res.ok){
                                        if(btns[i].innerText == 'Dodaj do ulubionych'){
                                            btns[i].innerText = 'Usuń z ulubionych'
                                        }
                                            else{
                                        btns[i].innerText = 'Dodaj do ulubionych'
                                        }
                                    }
                                    else{
                                        console.log("Not logged")
                                    }
                                })
                            })
                        }
                    </script>
                </div>
            </div>
            {% endblock %}
        </div>

    <script src="{% static 'sklep/base/base.js' %}"></script>
    {% block script %}
    {% endblock %}

    <svg class="icons">

        <symbol id="icon-search" viewBox="0 0 512 512">
          <path d="M500.3 443.7l-119.7-119.7c27.22-40.41 40.65-90.9 33.46-144.7C401.8 87.79 326.8 13.32 235.2 1.723C99.01-15.51-15.51 99.01 1.724 235.2c11.6 91.64 86.08 166.7 177.6 178.9c53.8 7.189 104.3-6.236 144.7-33.46l119.7 119.7c15.62 15.62 40.95 15.62 56.57 0C515.9 484.7 515.9 459.3 500.3 443.7zM79.1 208c0-70.58 57.42-128 128-128s128 57.42 128 128c0 70.58-57.42 128-128 128S79.1 278.6 79.1 208z"/>
        </symbol>

        
        </svg>

</body>
</html>

sklep/templates/sklep/base/faq.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="{% static 'sklep/base/base.css' %}" />
    </head>
    <body>
        {% include 'sklep/base/nav.html' %}
        <div class='faq-content'>
            {% for question in question_list%}
            <div class="question_card">
                <h1>{{question.question}}</h1>
                <p>{{question.answer}}</p>
                {%if user.is_superuser %}
                    <a href="{% url 'sklep:delete_faq' question.id %} "><svg xmlns="http://www.w3.org/2000/svg" width="35" height="35" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16" id="IconChangeColor"> <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z" id="mainIconPathAttribute"></path> <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" id="mainIconPathAttribute"></path> </svg></a>
                {%endif%}
            </div>
            {% endfor %}
            {%if user.is_superuser %}
            <div class="question_form">
                <form method="POST" action="">
                    {% csrf_token %}
                    Pytanie <input type="text" name="question" /><br />
                    Odpowiedz <input type="text" name="answer" /><br />
                    <input type="submit" value="Dodaj" />
                </form>
            <div>
            {%endif%}
        </div>
    </body>
</html>

sklep/templates/sklep/base/fav-products.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" text="type/css" href="{% static 'sklep/base/base.css' %}">
    <link href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.css"  rel="stylesheet"  type='text/css'>
    {% block style %}{% endblock %}
    <title>{% block title %}ProjektIO {% endblock %}</title>
    <script type="text/javascript">
        var user = '{{ request.user }}'
        function getToken(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        const csrftoken = getToken('csrftoken');
    </script>
    
</head>

<body>
    <div class="header">
        {%include 'sklep/base/nav.html'%}
    </div>
    
    <div class="containerforbackground">
        <div class="container">
            {% block content %}
            <div id="product-information">
                <p>
                    Ulubione produkty
                </p>
            </div>
            <div class="product-wrapper" id="product-wrapper">
                <div id="products">
                    {% for produkt in fav_products %}
                    <div id="product">
                        <div class="product-image">
                            <img src="{{ produkt.zdjecie_glowne.url }}">
                        </div>
                        <div class="product-information">
                            <div class="product-name">
                                <a class="product-name-style" href="{% url 'sklep:produkt_details' produkt.id %}">{{ produkt.marka }} {{ produkt.model }}</a>
                            </div>
                            <div class="product-price">{{ produkt.cena }} zł</div>
                            <div class="product-category">{{ produkt.podkategoria.nazwa }}</div>
                        </div>
                        <button id="{{produkt.id}}" class="add-to-fav-btn">{%csrf_token%}
                            Usuń z ulubionych
                        </button>
                    </div>
                    {% endfor %}
                    <script>
                        const prod_wrapper = document.querySelector('.product-wrapper')
                        const btns = prod_wrapper.querySelectorAll('button')
                        for (let i=0; i<btns.length; i++){
                            const token = '{{csrf_token}}'
                            btns[i].addEventListener('click', () => {
                                data = JSON.stringify({
                                    id: btns[i].id
                                })
                                fetch("", {
                                    method: 'POST',
                                    headers: {"X-CSRFToken": token},
                                    body: data
                                }).then((res) => {
                                    if(res.ok){
                                        document.location.reload()
                                    }
                                })
                            })
                        }
                    </script>
                </div>
            </div>
            {% endblock %}
        </div>

    <script src="{% static 'sklep/base/base.js' %}"></script>
    {% block script %}
    {% endblock %}

    <svg class="icons">

        <symbol id="icon-search" viewBox="0 0 512 512">
          <path d="M500.3 443.7l-119.7-119.7c27.22-40.41 40.65-90.9 33.46-144.7C401.8 87.79 326.8 13.32 235.2 1.723C99.01-15.51-15.51 99.01 1.724 235.2c11.6 91.64 86.08 166.7 177.6 178.9c53.8 7.189 104.3-6.236 144.7-33.46l119.7 119.7c15.62 15.62 40.95 15.62 56.57 0C515.9 484.7 515.9 459.3 500.3 443.7zM79.1 208c0-70.58 57.42-128 128-128s128 57.42 128 128c0 70.58-57.42 128-128 128S79.1 278.6 79.1 208z"/>
        </symbol>

        
        </svg>

</body>
</html>

sklep/templates/sklep/base/nav.html
{% load static %}
<nav>
    <div class="top-header">
        <div class="logo">
            <a href="{% url 'sklep:base' %}">
                <img src="{% static 'sklep/base/logo.png'  %}" alt="LOGO" />
            </a>
        </div>
        <div class="login-register-buttons">
            <a href="{% url 'sklep:faq' %}">FAQ</a>
            {% if user.is_authenticated %}
                <div class="login">
                    <p>Witaj <a class='user-buttons' href="{% url 'sklep:user_view' %}">{{ user.first_name }}</a></p>
                </div>
                <div class="pausebetween">
                    <p>|</p>
                </div>
                <div class="register">
                    <p><a class ='user-buttons' href="{% url 'sklep:logout_user' %}">Log Out</a></p>
                </div>
            {% else %}
                <div class="login">
                    <button id="login">
                        <a class="user-buttons" href="{% url 'sklep:login_user' %}">LOGOWANIE</a>
                    </button>
                </div>
                <div class="pausebetween">
                    <p>|</p>
                </div>
                <div class="register">
                    <button id="register">
                        <a class ='user-buttons' href="{% url 'sklep:register' %}">REJESTRACJA</a>
                    </button>
                </div>
            {% endif %}
        </div>
    </div>
    <div class="bottom-header">
        <div class="bottom-header-left-side">

            <div class="category-button-box hide" id="category-btn-box">
                <button id="show-hide-categories">
                    <i class="fa fa-bars" aria-hidden="true"></i>
                </button>
                <p>Kategorie</p>
            </div>
            
            <div class="categories" id="category-list">
                {%for kat in request.session.nav_cat%}
                <div class="category-element">
                    <p class="main-category">
                        <a href= "{%url 'sklep:filter_view' kat%}" >{{kat}}</a>
                    </p>
                </div>
                {%endfor%}
            </div>
        </div>
        <div class="bottom-header-right-side">

            <form action="{% url 'sklep:searchProduct' %}"  method="get" class="search-box">
                <input type="text" class="search-control" name = "query" placeholder="Szukaj..." id="search-input">
                <button class="search-btn">
                    <svg class="icon-search" viewBox="0 0 512 512">
                        <path d="M500.3 443.7l-119.7-119.7c27.22-40.41 40.65-90.9 33.46-144.7C401.8 87.79 326.8 13.32 235.2 1.723C99.01-15.51-15.51 99.01 1.724 235.2c11.6 91.64 86.08 166.7 177.6 178.9c53.8 7.189 104.3-6.236 144.7-33.46l119.7 119.7c15.62 15.62 40.95 15.62 56.57 0C515.9 484.7 515.9 459.3 500.3 443.7zM79.1 208c0-70.58 57.42-128 128-128s128 57.42 128 128c0 70.58-57.42 128-128 128S79.1 278.6 79.1 208z"/>
                    </svg>
                </button>
            </form>
            <div class="shopping-basket">
                <button id="basket" >
                    <a href="{% url 'sklep:shopping_cart' %}">
                        <svg class="icon-basket" viewBox="0 0 576 512">
                            <path d="M96 0C107.5 0 117.4 8.19 119.6 19.51L121.1 32H541.8C562.1 32 578.3 52.25 572.6 72.66L518.6 264.7C514.7 278.5 502.1 288 487.8 288H170.7L179.9 336H488C501.3 336 512 346.7 512 360C512 373.3 501.3 384 488 384H159.1C148.5 384 138.6 375.8 136.4 364.5L76.14 48H24C10.75 48 0 37.25 0 24C0 10.75 10.75 0 24 0H96zM128 464C128 437.5 149.5 416 176 416C202.5 416 224 437.5 224 464C224 490.5 202.5 512 176 512C149.5 512 128 490.5 128 464zM512 464C512 490.5 490.5 512 464 512C437.5 512 416 490.5 416 464C416 437.5 437.5 416 464 416C490.5 416 512 437.5 512 464z"/>
                        </svg>
                    </a>
                    <a href="{% url 'sklep:fav_view' %}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="35" height="35" fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16" id="IconChangeColor"> <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z" id="mainIconPathAttribute"></path> </svg>
                    </a>
                </button>
            </div>
        </div>
    </div>
</nav>